FROM ghcr.io/astral-sh/uv:python3.14-trixie

# Set the working directory to /app
WORKDIR /app

RUN apt-get update && apt-get install -y make

COPY Makefile ./
COPY pyproject.toml ./
RUN make install

COPY . /app
RUN make install