# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: d91c27b
_src_path: https://github.com/MartinBernstorff/nimble-python-template
email: martinbernstorff@gmail.com
full_name: Martin Bernstorff
github_username: MartinBernstorff
package_name: lumberman
project_name: lumberman
project_slug: lumberman
python_version: '3.10'
release_docker_image: false
release_package: true
